import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
export default function EyeDiagramJitterArticle(){return <>
<section id="eye-basics"><h2>眼图的意义与叠加</h2><p>眼图把长串行数据按一个或多个 UI 切片并叠加，把不同码型、周期、噪声和抖动的 worst case 同时显示。单次实时波形只代表某个码型，眼图更适合整体判断链路裕量。</p><ArticleFigure src="images/knowledge/si-pi/eye-overlay-patterns.webp" fullSrc="images/knowledge/si-pi/eye-overlay-patterns-hd.jpg" alt="多码型叠加形成眼图" caption="000、001、010…不同跳变路径叠加，形成眼睛形状并暴露最差边沿。" sourcePage="89"/></section>
<section id="eye-metrics"><h2>眼高、眼宽与模板</h2><p>眼高以 mV 表示，反映幅值、插损、噪声和信噪比；眼宽以 UI 表示，反映可采样窗口和抖动。<FormulaText text="1UI=1/T_{bit}" />，10Gbps 时 1UI=0.1ns。协议眼图模板定义禁入区域，还规定测试点、终端和夹具。</p><ArticleFigure src="images/knowledge/si-pi/eye-height-width.webp" fullSrc="images/knowledge/si-pi/eye-height-width-hd.jpg" alt="眼高眼宽示意" caption="垂直开口是眼高，水平开口是眼宽；两者分别受幅度噪声与定时抖动主导。" sourcePage="90"/><ArticleFigure src="images/knowledge/si-pi/hdmi-eye-mask.webp" fullSrc="images/knowledge/si-pi/hdmi-eye-mask-hd.jpg" alt="HDMI 眼图模板" caption="HDMI 1.4 源端模板在 TP1 指定测试，波形不得侵入模板禁区。" sourcePage="92"/></section>
<section id="isi-jitter"><h2>码间干扰与抖动</h2><p>不同码型含有不同频谱，链路高频插损更大，所以 0101 跳变密集码型比 111000 更易衰减；前一 bit 的尾巴影响后一 bit，就是 ISI。ISI 同时压缩眼高和眼宽；Jitter 主要表现为交叉点水平扩散。</p><ArticleFigure src="images/knowledge/si-pi/isi-channel-loss.webp" fullSrc="images/knowledge/si-pi/isi-channel-loss-hd.jpg" alt="8inch PCB 走线引起 ISI" caption="经过信道后连续位幅值不一，眼高眼宽都比无 ISI 时明显下降。" sourcePage="94"/><ArticleFigure src="images/knowledge/si-pi/isi-eye-closing.webp" fullSrc="images/knowledge/si-pi/isi-eye-closing-hd.jpg" alt="ISI 前后眼图" caption="频率相关损耗使不同码型到达接收端的幅值和边沿不同，眼图闭合且不对称。" sourcePage="91"/></section>
<section id="equalization"><h2>接收端均衡</h2><p>接收均衡可理解为高通+增益：相对压低低频、放大高频，抵消信道的频率相关衰减，使均衡后总响应更平坦。增益不是越大越好，过度均衡会同时放大噪声。</p><ArticleFigure src="images/knowledge/si-pi/receiver-equalization.webp" fullSrc="images/knowledge/si-pi/receiver-equalization-hd.jpg" alt="接收均衡补偿信道" caption="70inch FR4 上的 2.5Gbps 信号经 DS25BR110 均衡后，眼高恢复到约 600mV，眼图重新打开。" sourcePage="96"/></section>
<section id="emphasis"><h2>预加重与去加重</h2><p>两者都在发送端平衡高低频：预加重提高跳变后的第一个 bit，去加重降低连续相同 bit 的后续幅值。经过高频损耗更大的信道后，不同频率分量更接近，眼高和眼宽恢复。PCIE3、USB3、HDMI1.4+ 等广泛使用。</p><ArticleFigure src="images/knowledge/si-pi/preemphasis-eye.webp" fullSrc="images/knowledge/si-pi/preemphasis-eye-hd.jpg" alt="预加重前后眼图" caption="首个跳变 bit 被提高，长距离传输后的眼图开口更大。" sourcePage="97"/><ArticleFigure src="images/knowledge/si-pi/deemphasis-eye.webp" fullSrc="images/knowledge/si-pi/deemphasis-eye-hd.jpg" alt="去加重前后眼图" caption="连续相同比特被降低，相对突出跳变高频分量，补偿链路插损。" sourcePage="98"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>眼高与眼宽分别看什么？</summary><p>眼高看幅值/噪声/插损，眼宽看采样窗口和抖动。</p></details><details><summary>ISI 为什么与码型有关？</summary><p>不同跳变密度包含不同频谱，而信道对高低频衰减不同。</p></details><details><summary>预加重和去加重的共同目的？</summary><p>在发送端调整高低频相对幅度，抵消信道高频损耗并扩大接收眼图。</p></details></section></>}
