import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";

export default function GigabitEthernetArticle() {
  return <>
    <section id="phy-topology"><h2>千兆网拓扑与 PHY 架构</h2><p>1000BASE-T 的硬件链路是 MAC→PHY→网络变压器→RJ45→双绞线。MAC 与 PHY 之间用 RGMII 传数据、MDIO 做管理；PHY 与网变之间的 MDI 用四对双向差分线。PHY 内部包含 ADC/DAC、回声消除、FFE/DFE、PCS、PLL 与多路电源。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-topology.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-topology-hd.jpg" alt="千兆以太网接口拓扑" caption="RGMII/MDIO 位于数字侧，MDI 位于模拟线缆侧，网变提供共模抑制和电气隔离。" sourcePage="46" /><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-yt8531-schematic.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-yt8531-schematic-hd.jpg" alt="YT8531 千兆 PHY 原理图" caption="RGMII 串 33Ω，MDIO/MDC/INT 上拉，25MHz 晶振、1.0V 模拟/数字电源和 RSET 都需按手册实现。" sourcePage="47" /></section>
    <section id="rgmii"><h2>RGMII 接口与 2ns 延时</h2><p>RGMII 共 12 根单端线：TX 与 RX 各有 CLK、CTL 和 D[3:0] 六根。125MHz DDR 双边沿传 4bit，<FormulaText text="125MHz×2×4=1000Mbps" />。时钟若与数据同相，采样沿落在跳变处；启用约 2ns 延时后，采样沿移到 8ns 周期的数据眼中心。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-rgmii-2ns.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-rgmii-2ns-hd.jpg" alt="RGMII 2ns 时钟延时" caption="MAC、PHY 或 PCB 三者只能明确由一处实现延时，重复或遗漏都会破坏建立保持裕量。" sourcePage="48" /></section>
    <section id="mdio"><h2>MDIO 管理接口</h2><p>MDIO/MDC 用于读写 PHY 寄存器、地址与 Link 状态，可管理最多 32 个 PHY。MDIO 是三态双向线而非 IIC 开漏，但仍需 1.5~10kΩ 上拉；不同器件最高 MDC 可能为 2.5、12.5 或 25MHz，必须查表。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-mdio-table.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-mdio-table-hd.jpg" alt="MDIO 时序参数表" caption="示例中 MDC 周期最小 80ns、MDIO 建立保持各 10ns；不要只凭接口名称假定速度。" sourcePage="48" /></section>
    <section id="mdi-pam5"><h2>MDI 接口与 PAM5 编码</h2><p>千兆 MDI 的四对线同时收发，回声消除器分离本端发送和远端接收。PAM5 用 0、±0.5、±1V 五个幅度，每个 125MHz 符号承载 2bit，四对合计 <FormulaText text="125M×2×4=1000Mbps" />；最高基频仍约 125MHz。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-pam5-wave.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-pam5-wave-hd.jpg" alt="千兆以太网 PAM5 波形" caption="五电平提高符号效率；四对双绞线并行且每对全双工。" sourcePage="49" /></section>
    <section id="rj45"><h2>RJ45 线序与网络变压器</h2><p>T568B 中 A 对为 1/2、B 对为 3/6、C 对为 4/5、D 对为 7/8，不能把 1~8 顺序相邻误当成四对。Bob Smith 端接常用四个 75Ω 汇到共模点，再经 1nF/2kV 接机壳地；带网变 RJ45 适合紧凑消费方案，独立网变便于工业级防护。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-rj45-t568b.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-rj45-t568b-hd.jpg" alt="RJ45 T568B 线序" caption="3 与 6 是一对、4 与 5 是一对；线序错误可能导致只能百兆或完全不通。" sourcePage="50" /><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-transformer-rj45.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-transformer-rj45-hd.jpg" alt="网变与 RJ45 电路" caption="网络变压器、Bob Smith 端接、高压电容和机壳地构成隔离与共模泄放路径。" sourcePage="50" /></section>
    <section id="speed-diff"><h2>十兆、百兆、千兆的区别</h2><div className="comparison-table-wrap"><table className="comparison-table"><caption>铜缆以太网物理层</caption><thead><tr><th scope="col">模式</th><th scope="col">线对/编码</th><th scope="col">典型特点</th></tr></thead><tbody><tr><th scope="row">10BASE-T</th><td>2 对、曼彻斯特</td><td>约 20MHz，幅度较大</td></tr><tr><th scope="row">100BASE-TX</th><td>2 对、MLT-3</td><td>125MHz×8b/10b=100Mbps</td></tr><tr><th scope="row">1000BASE-T</th><td>4 对、PAM5</td><td>四对均双向，眼图难直接分离</td></tr></tbody></table></div></section>
    <section id="pcb-design"><h2>千兆网 PCB 设计</h2><p>RGMII 按 50Ω 单端控制，TX/RX 数据分别以本组时钟为基准控制 &lt;120mil，线长 &lt;5inch。MDI 按 100Ω 差分，对内 &lt;5mil、对间约 100~200mil、线长 &lt;2inch。RJ45 与网变靠近，网变下方挖空；HGND 与板内 GND/信号/电源至少隔 20mil。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-rgmii-pcb-table.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-rgmii-pcb-table-hd.jpg" alt="RGMII PCB 约束表" caption="数据只与本方向时钟等长；RX 源端串阻靠 PHY，TX 源端串阻靠 MAC。" sourcePage="53" /><ArticleFigure src="images/knowledge/high-speed-interfaces/gige-transformer-keepout.webp" fullSrc="images/knowledge/high-speed-interfaces/gige-transformer-keepout-hd.jpg" alt="网变下方挖空" caption="跨隔离变压器下方挖空所有铜层，避免寄生电容把共模噪声耦合到线缆侧。" sourcePage="53" /></section>
    <section id="interview"><h2>面试自测</h2><details><summary>RGMII 为什么是 125MHz 却能传 1Gbps？</summary><p>DDR 双边沿、每沿 4bit：125M×2×4=1Gbps。</p></details><details><summary>2ns 延时应放在哪里？</summary><p>可由 MAC、PHY 或 PCB 实现，但必须明确只有一处，保证采样沿落在数据稳定区。</p></details><details><summary>千兆网为何用四对线？</summary><p>PAM5 每符号约 2bit，125M×2bit×4 对达到 1Gbps，并用回声消除实现每对全双工。</p></details></section>
  </>;
}
