import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
import WorkedExample from "../WorkedExample.jsx";

export default function HdmiPcieUsbArticle() {
  return <>
    <section id="hdmi-arch"><h2>HDMI 接口架构与 TMDS 电平</h2><p>HDMI 2.0 以前包含一对 TMDS 时钟、三对 TMDS 数据，以及 DDC SCL/SDA、HPD、CEC 四根低速线和 5V 电源。TMDS 单端 50Ω、差分 100Ω，源端共模接近 3.3V、差模约 ±400~600mV；接收端至少需要 ±150mV。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/hdmi-soc-schematic.webp" fullSrc="images/knowledge/high-speed-interfaces/hdmi-soc-schematic-hd.jpg" alt="SOC HDMI 接口原理图" caption="高速差分用超低电容 TVS，DDC/HPD/CEC 用单端保护；DDC 是固定 5V 的 IIC，需要电平转换。" sourcePage="55" /><ArticleFigure src="images/knowledge/high-speed-interfaces/hdmi-tmds-topology.webp" fullSrc="images/knowledge/high-speed-interfaces/hdmi-tmds-topology-hd.jpg" alt="HDMI TMDS 拓扑" caption="接收端 50Ω 上拉形成 TMDS 电流模式链路，差分对按 100Ω 控制。" sourcePage="56" /></section>
    <section id="hdmi-speed"><h2>HDMI 速率等级与其他引脚</h2><p>HDMI 1.4/2.0/2.1 总带宽约 10.2/18/48Gbps；2.1 改用四对 FRL SERDES 并内嵌时钟。DDC 上拉约 1.5~2kΩ，HPD 高表示接收设备接入；接收端拉低 HPD 至少 100ms 可要求源端重新读取 EDID。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/hdmi-rate-table.webp" fullSrc="images/knowledge/high-speed-interfaces/hdmi-rate-table-hd.jpg" alt="HDMI 版本速率表" caption="物理设计关注单对线速率：HDMI 2.0 为 6Gbps，2.1 FRL 最高 12Gbps。" sourcePage="57" /></section>
    <section id="hdmi-pcb"><h2>HDMI 的 PCB 设计</h2><p>差分 100Ω±10%，P/N 对内偏差 &lt;6mil，时钟与数据组间 &lt;480mil；2.0/2.1 线长建议分别 &lt;6/&lt;4inch。过孔≤2 个，对间距按 5W/7W，TVS 结电容分别 &lt;0.35/&lt;0.15pF，并给换层与防护器件布回流地孔。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/hdmi-pcb-table.webp" fullSrc="images/knowledge/high-speed-interfaces/hdmi-pcb-table-hd.jpg" alt="HDMI PCB 设计约束" caption="速率越高，线长、过孔、间距与 ESD 结电容要求越严；连接器焊盘可局部挖空补偿阻抗。" sourcePage="59" /></section>
    <section id="pcie"><h2>PCIE 接口与电路设计</h2><p>每个 lane 包含一对 TX 和一对 RX，X1~X16 表示 lane 数。Gen1/2 用 8b/10b，Gen3~5 用 128b/130b，Gen6 转 PAM4。板卡金手指还提供 12V、3.3V、3.3V_AUX、100MHz REFCLK、PERST#、WAKE#、PRSNT 与 SMBUS；高速数据内嵌时钟，因此不同 lane 不做组间等长。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/pcie-gen-table.webp" fullSrc="images/knowledge/high-speed-interfaces/pcie-gen-table-hd.jpg" alt="PCIE 代际速率表" caption="Gen2 X16 有效单向带宽=5Gbps×80%×16÷8=8GB/s；编码效率不可漏算。" sourcePage="60" /><ArticleFigure src="images/knowledge/high-speed-interfaces/pcie-edge-schematic.webp" fullSrc="images/knowledge/high-speed-interfaces/pcie-edge-schematic-hd.jpg" alt="PCIE 金手指电路" caption="RC/EP 方向决定 TX/RX 命名；EP 发送端的交流耦合电容靠近金手指。" sourcePage="61" /><ArticleFigure src="images/knowledge/high-speed-interfaces/pcie-ac-coupling.webp" fullSrc="images/knowledge/high-speed-interfaces/pcie-ac-coupling-hd.jpg" alt="PCIE 交流耦合电容" caption="Gen2 常用 100nF、Gen3 常用 220nF 0201；只放在每条链路的发送端。" sourcePage="63" /></section>
    <section id="usb"><h2>USB 接口与电路设计</h2><p>USB 2.0 的 D+/D− 为 480Mbps 半双工；USB 3.0 额外增加 SSTX 与 SSRX 两对 5Gbps 差分，实现全双工。VBUS 为 5V±5%，Host 用负载开关限流；MT9700 近似满足 <FormulaText text="I_{limit}=6.8/R_{SET}" />（A、kΩ），USB3 常设 1.1~1.3A 留压降余量。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/usb3-schematic.webp" fullSrc="images/knowledge/high-speed-interfaces/usb3-schematic-hd.jpg" alt="USB3 Host 接口电路" caption="连接器到芯片依次布 TVS、可选共模电感、SSTX 耦合电容；三对差分都要低电容 ESD。" sourcePage="63" /><ArticleFigure src="images/knowledge/high-speed-interfaces/usb-mt9700.webp" fullSrc="images/knowledge/high-speed-interfaces/usb-mt9700-hd.jpg" alt="MT9700 USB 限流电路" caption="EN 控制 VBUS，ISET 电阻设置限流；5.1kΩ 对应约 1.3A。" sourcePage="64" /><WorkedExample title="USB3 Host 限流电阻" given={["目标限流约 1.2A", "MT9700 关系 I=6.8/RSET（A、kΩ）"]} calculation={["RSET=6.8/1.2≈5.67kΩ", "选 E24 5.6kΩ，名义限流约 1.21A"]} verification={["高于 USB3 0.9A 额定供电并留线缆压降余量", "低于接口、连接器和电源开关允许电流"]} answer="取 5.6kΩ 得到约 1.21A，并继续校核容差、温升与短路保护。" /></section>
    <section id="usb-pcie-pcb"><h2>PCIE 与 USB 的 PCB 设计对比</h2><div className="comparison-table-wrap"><table className="comparison-table"><caption>高速差分 PCB 关键约束</caption><thead><tr><th scope="col">项目</th><th scope="col">PCIE</th><th scope="col">USB</th></tr></thead><tbody><tr><th scope="row">阻抗</th><td>85Ω±10%</td><td>90Ω±10%</td></tr><tr><th scope="row">对内偏差</th><td>&lt;6mil</td><td>USB2 &lt;20mil；USB3 &lt;6mil</td></tr><tr><th scope="row">过孔</th><td>≤2</td><td>USB2 ≤4；USB3 ≤2</td></tr><tr><th scope="row">保护</th><td>内部接口通常不加 TVS</td><td>热插拔外部接口必须加低电容 ESD</td></tr></tbody></table></div><p>两者都内嵌时钟，只要求 P/N 对内等长，不要求 TX/RX 或不同 lane 对间等长；交流耦合电容均位于发送端。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/usb-pcb-table.webp" fullSrc="images/knowledge/high-speed-interfaces/usb-pcb-table-hd.jpg" alt="USB PCB 约束表" caption="USB3 与 PCIE 在等长、过孔和耦合方式上相似，但阻抗与热插拔防护不同。" sourcePage="65" /></section>
    <section id="interview"><h2>面试自测</h2><details><summary>HDMI 2.0 与 2.1 的时钟结构有什么变化？</summary><p>2.0 以前是一对独立时钟加三对数据；2.1 FRL 使用四对 SERDES 并内嵌时钟。</p></details><details><summary>PCIE X4 表示什么？</summary><p>四个 lane，每 lane 各有一对发送和一对接收；总带宽还要乘编码效率并除以 8 换成 Byte/s。</p></details><details><summary>USB 与 PCIE 的 PCB 最大区别是什么？</summary><p>两者都是内嵌时钟高速差分，但 USB 面向热插拔外部接口，必须重视 ESD、VBUS 限流和共模辐射。</p></details></section>
  </>;
}
