import ArticleFigure from "../ArticleFigure.jsx";
import WorkedExample from "../WorkedExample.jsx";
export default function LengthMatchingArticle(){return <>
<section id="why"><h2>等长的原因与等时本质</h2><p>等长服务于建立/保持时间：接收端必须在同一采样窗口看到时钟和数据。真正目标是“等时”，所以还要计入内外层传播速度、过孔、连接器和封装 pin delay；一组信号最好走同层并一起换层。</p><ArticleFigure src="images/knowledge/si-pi/clock-data-setup-hold.webp" fullSrc="images/knowledge/si-pi/clock-data-setup-hold-hd.jpg" alt="时钟数据建立保持窗口" caption="数据相对采样时钟到达，而不是任意数据线彼此比较；等长基准必须先找对。" sourcePage="46"/></section>
<section id="single-ended"><h2>单端总线按谁等长</h2><p>DDR 地址/命令相对 CK，DQ/DM 按每个 Byte 相对 DQS；eMMC 写入相对 CLK、读取相对 Data Strobe；RGMII 的 TX 和 RX 各自相对本方向时钟；SPI、并口 ADC/DAC 与 PCLK/SCLK 配组。</p><ArticleFigure src="images/knowledge/si-pi/ddr-length-groups.webp" fullSrc="images/knowledge/si-pi/ddr-length-groups-hd.jpg" alt="DDR 等长分组" caption="地址命令、两个 DQ Byte lane 和差分时钟分别有自己的等长基准。" sourcePage="48"/><ArticleFigure src="images/knowledge/si-pi/lpddr4-skew-table.webp" fullSrc="images/knowledge/si-pi/lpddr4-skew-table-hd.jpg" alt="LPDDR4 时延约束" caption="3200Mbps 条件下 DQ↔DQS、DM↔DQS、地址↔CLK 常要求 ≤16ps，约合 100mil。" sourcePage="49"/></section>
<section id="differential"><h2>差分对内与对间等长</h2><p>P/N 对内通常控制 ±5mil；不等会把差模转成共模，引起零点漂移、眼图收缩、共模辐射和谐振峰。LVDS、MIPI、HDMI 2.0 有独立时钟时，数据对还要相对时钟做组间等长。</p><ArticleFigure src="images/knowledge/si-pi/differential-skew-eyes.webp" fullSrc="images/knowledge/si-pi/differential-skew-eyes-hd.jpg" alt="P N skew 对眼图影响" caption="从 0ps 到 25ps skew，眼高和眼宽持续收缩，插损谐振点也随 skew 增大而恶化。" sourcePage="55"/><ArticleFigure src="images/knowledge/si-pi/interpair-clock-matching.webp" fullSrc="images/knowledge/si-pi/interpair-clock-matching-hd.jpg" alt="MIPI 对间时钟等长" caption="MIPI D-PHY 数据对相对时钟对控制组内时差，同时每对内部仍需 P/N 对内等长。" sourcePage="57"/></section>
<section id="embedded-clock"><h2>内嵌时钟接口</h2><p>USB、PCIe、DisplayPort 和以太网接收端用 CDR 恢复采样时钟，因此通常不要求各 lane 与独立采样时钟逐一等长；但 CDR 不代表 lane 间偏斜无限制。多 lane 协议仍有 deskew 缓冲、通道绑定和总偏斜预算，必须按具体代际规范执行；每对 P/N 的对内偏斜也要满足规范。</p><ArticleFigure src="images/knowledge/si-pi/embedded-clock-interfaces.webp" fullSrc="images/knowledge/si-pi/embedded-clock-interfaces-hd.jpg" alt="内嵌时钟高速接口" caption="CDR 放宽了与独立时钟的匹配要求，但多 lane 仍受协议 deskew 与总偏斜预算约束。" sourcePage="59"/></section>
<section id="implementation"><h2>PCB 绕等长实现</h2><p>在 EDA 中用时钟设 target/match group，先完成主走线再补偿。就近补偿优于把蛇形堆在一端；P/N 一起绕，补偿段间距不超过正常间距两倍；蛇形中心距尽量 ≥3W（更严可 4W），避免自耦。器件和过孔也要对称。</p><ArticleFigure src="images/knowledge/si-pi/near-end-length-tuning.webp" fullSrc="images/knowledge/si-pi/near-end-length-tuning-hd.jpg" alt="就近补偿与一次性补偿" caption="哪里产生长度差异就在哪里补偿，仿真眼图优于在末端集中绕线。" sourcePage="63"/><ArticleFigure src="images/knowledge/si-pi/meander-spacing-rules.webp" fullSrc="images/knowledge/si-pi/meander-spacing-rules-hd.jpg" alt="蛇形线间距规则" caption="平行蛇形线会自耦，中心距至少 3W/4W，减少绕线数量与平行长度。" sourcePage="66"/><WorkedExample title="LPDDR4 16ps 约束换算" given={["板内传播约 6000mil/ns","时延要求 ≤16ps"]} calculation={["6000mil/ns×0.016ns=96mil"]} verification={["与课件约 100mil 一致","需计入过孔和封装时延"]} answer="16ps 约等于 96mil，工程上可记为约 100mil，但最终以时延约束为准。"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>等长为什么不是简单比较所有数据线？</summary><p>采样关系决定基准，数据要相对自己的时钟/DQS 等时到达。</p></details><details><summary>哪些接口不做对间等长？</summary><p>USB、PCIE、DP、千兆网等内嵌时钟接口。</p></details><details><summary>蛇形线为什么不能太密？</summary><p>相邻平行段会自耦，实际时延低于几何长度预期，并增加串扰与损耗。</p></details></section></>}
