import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
import WorkedExample from "../WorkedExample.jsx";

export default function LvdsArticle() {
  return <>
    <section id="differential-basics"><h2>差分信号与单端的区别</h2><p>单端信号用一根线相对 GND 判电平，结构简单但摆幅大、抗扰弱。差分信号用 P/N 两根等幅反相线，接收器判 <FormulaText text="V_D=V_P-V_N" />；外界共模噪声同时耦合到两线，做差后大幅抵消。小摆幅还可在相同压摆率下获得更快边沿和更低 EMI。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/diff-single-wave.webp" fullSrc="images/knowledge/high-speed-interfaces/diff-single-wave-hd.jpg" alt="单端信号波形" caption="单端信号完全依赖 GND 参考，地弹和回流路径变化会直接改变接收裕量。" sourcePage="34" /><ArticleFigure src="images/knowledge/high-speed-interfaces/diff-pair-wave.webp" fullSrc="images/knowledge/high-speed-interfaces/diff-pair-wave-hd.jpg" alt="差分信号 P N 波形" caption="P/N 等幅反相，接收端用差模判决；对称耦合的噪声主要落在共模。" sourcePage="34" /></section>
    <section id="differential-interfaces"><h2>常见差分接口一览</h2><p>RS485、以太网、HDMI、USB、PCIE、LVDS/MIPI 都用差分，但电平、阻抗和时钟组织不同。USB 常为 90Ω 差分，LVDS/MIPI/HDMI 与网口 MDI 多为 100Ω；不能因为“都是差分”就互连。</p><div className="application-list"><article><h3>随路或内嵌时钟</h3><p>LVDS/LCD 常用 1 对时钟+多对数据；网口、PCIE、USB3 数据流内嵌时钟并由 CDR 恢复。</p></article><article><h3>多电平编码</h3><p>千兆网 PAM5、10G PAM16、PCIE Gen6 PAM4 用多电平提高每个符号携带的信息量。</p></article><article><h3>低功耗双模式</h3><p>MIPI 在约 200mV 的高速差分模式与低功耗单端控制模式之间切换。</p></article></div></section>
    <section id="lvds-standard"><h2>LVDS 电气标准与电平</h2><p>TIA/EIA-644 的发送端以约 3.5mA 恒流源换向，电流流过接收端 100Ω 端接得到约 ±350mV 差模，共模约 1.2V。端接应靠近接收器；若 FPGA/SOC 已开内部 100Ω，就不要再并外部电阻。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/lvds-current-model.webp" fullSrc="images/knowledge/high-speed-interfaces/lvds-current-model-hd.jpg" alt="LVDS 恒流源模型" caption="3.5mA×100Ω≈350mV；电流方向翻转代表 0/1，PCB 差分阻抗也按 100Ω 控制。" sourcePage="38" /><ArticleFigure src="images/knowledge/high-speed-interfaces/lvds-dc-spec.webp" fullSrc="images/knowledge/high-speed-interfaces/lvds-dc-spec-hd.jpg" alt="LVDS 直流电气参数" caption="典型共模 1.2V，接收最小差模约 ±100mV，超过器件最大输入范围也可能损坏。" sourcePage="40" /></section>
    <section id="clock-data"><h2>时钟与数据的关系</h2><p>LVDS 可 1:1 传输，也可串并转换为 1:N：Camera Link 常用 1:7，HDMI TMDS 用 1:10。SDR 每周期采一次，DDR 双边沿采样，因此 297MHz 时钟可承载 594Mbps 数据；设计时要分清“时钟频率”和“线速率”。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/lvds-waveform.webp" fullSrc="images/knowledge/high-speed-interfaces/lvds-waveform-hd.jpg" alt="LVDS 时钟数据关系" caption="接收端要在数据眼中心采样，时钟与各数据对的偏差直接压缩建立保持窗口。" sourcePage="39" /></section>
    <section id="length-matching"><h2>LVDS 等长设计</h2><p>每对 P/N 对内通常控制 5mil，并保持等间距、同时换层。多组数据以时钟对为基准可控制 ±100mil；不同独立组通常无需严格互等长。布线困难时可用 training 或 FPGA 相位步进在接收端补偿。</p><WorkedExample title="LVDS 数据组等长裕量" given={["CLK=1000mil，DATA0=910mil，DATA1=1090mil", "约 6.7inch/ns，链路 1.2Gbps DDR"]} calculation={["最大相对偏差为 ±90mil，小于 ±100mil 目标", "90mil 对应约 13ps，远小于 1.67ns 时钟周期"]} verification={["P/N 对内仍需单独满足 5mil", "连接器、过孔和层换也要对称"]} answer="组内相对时钟的 ±90mil 合格，但必须继续检查每对内部偏差。" /></section>
    <section id="long-distance"><h2>长距离衰减与均衡中继</h2><p>若发送 ±350mV、接收至少 ±100mV，链路允许的幅度插损约 <FormulaText text="20log(100/350)≈-10dB" />。预算被 PCB、连接器和线缆耗尽时，可提高驱动电流、加入 LVDS Buffer，或用均衡器补偿高频损耗和码间干扰。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/lvds-eq-eye.webp" fullSrc="images/knowledge/high-speed-interfaces/lvds-eq-eye-hd.jpg" alt="LVDS 均衡前后眼图" caption="70inch FR-4、2.5Gbps PRBS-7 链路中，均衡恢复高频分量并重新打开眼图。" sourcePage="44" /><aside className="article-callout"><strong>工程边界：</strong>加大驱动只能提高幅度，均衡才针对频率相关插损导致的 ISI；二者不能混为一谈。</aside></section>
    <section id="interview"><h2>面试自测</h2><details><summary>LVDS 的 350mV 怎么来的？</summary><p>约 3.5mA 恒流流经接收端 100Ω 端接，得到约 350mV 差分电压。</p></details><details><summary>差分线为什么还需要参考平面？</summary><p>实际耦合并非完全局限在 P/N 之间，共模电流、过孔换层和不对称都会依赖连续参考平面。</p></details><details><summary>什么时候用均衡而不是加大驱动？</summary><p>当高频分量比低频衰减更大、眼图因 ISI 闭合时，应做频率补偿；纯幅度不足才优先增加驱动。</p></details></section>
  </>;
}
