import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
import WorkedExample from "../WorkedExample.jsx";
export default function PiPdnArticle(){return <>
<section id="definitions"><h2>SI、PI 与常见问题</h2><p>SI 关注信号从驱动端经过 PCB/线缆到接收端后，幅值、形态和时序是否仍可判决；PI 关注电源系统能否在负载动态变化时提供稳定、低噪声的电压与电流。串扰、反射、插损、时延、EMC 与供电噪声会相互耦合，不能孤立处理。</p></section>
<section id="pdn-model"><h2>PDN 组成与目标阻抗</h2><p>PDN 从低到高频由 VRM、去耦电容、板级电源/地平面、IC 封装和片上电容接力。设计目标不是某个直流电阻，而是在工作频段内满足 <FormulaText text="Z_{target}(f)=ΔV(f)/ΔI(f)" />。</p><ArticleFigure src="images/knowledge/si-pi/pdn-frequency-bands.webp" fullSrc="images/knowledge/si-pi/pdn-frequency-bands-hd.jpg" alt="PDN 五部分频率范围" caption="VRM 负责低频，去耦与平面覆盖中高频，封装和片上电容处理最高频瞬态。" sourcePage="7"/><WorkedExample title="3.3V 电源的 PDN 目标阻抗" given={["供电 3.3V，允许波动 5%","电流阶跃按 1A 评估"]} calculation={["ΔVmax=3.3×5%=0.165V","Ztarget=0.165V/1A=0.165Ω"]} verification={["目标覆盖规定频段，不是万用表直流阻值","需要阻抗扫描或仿真检查谐振峰"]} answer="该电源在目标频段内的 PDN 阻抗应尽量低于 0.165Ω。"/></section>
<section id="ssn"><h2>SSN 同时开关噪声</h2><p>大量 IO 同时翻转引起地弹/电源反弹，近似 <FormulaText text="ΔV=N×L_{loop}×Δi/Δt" />。DDR 位宽、速率和边沿越大，眼图越容易收缩；优化层叠、拓宽平面、增加贴近 BGA 的小封装去耦可降低回路电感。</p><ArticleFigure src="images/knowledge/si-pi/ssn-eye-comparison.webp" fullSrc="images/knowledge/si-pi/ssn-eye-comparison-hd.jpg" alt="DDR SSN 眼图对比" caption="不计 PDN、16bit 与 64bit 同时翻转的仿真显示：开关数量增加会明显压缩眼高眼宽。" sourcePage="10"/></section>
<section id="vsense"><h2>远端反馈与压降补偿</h2><p>CPU/GPU/FPGA 核心电源和 DDR VTT 电流变化快，电源铜皮压降会随负载变化。VSENSE 应从芯片 BGA 供电点以 Kelvin 差分线返回控制器，而不是只在稳压器输出电容处取样。</p><ArticleFigure src="images/knowledge/si-pi/vsense-rk3588.webp" fullSrc="images/knowledge/si-pi/vsense-rk3588-hd.jpg" alt="RK3588 核心电源远端反馈" caption="反馈点落在负载芯片供电端，控制器补偿 PCB 铜皮和过孔上的动态压降。" sourcePage="12"/><ArticleFigure src="images/knowledge/si-pi/vsense-tps548b28.webp" fullSrc="images/knowledge/si-pi/vsense-tps548b28-hd.jpg" alt="TPS548B28 差分 VSENSE" caption="FB 与 VSNS− 成对从负载端回采，避免大电流回路压降混入参考。" sourcePage="13"/></section>
<section id="decoupling"><h2>去耦电容与板级设计</h2><p>不同容值、类型和封装并联覆盖宽频段；小容值通常用更小封装以降低 ESR/ESL。每个电源脚就近放一颗，连接短且粗；平面铜皮不要被密集过孔割裂，换层用多颗电源/地过孔并联降低寄生电感。</p><ArticleFigure src="images/knowledge/si-pi/decoupling-capacitor-layout.webp" fullSrc="images/knowledge/si-pi/decoupling-capacitor-layout-hd.jpg" alt="去耦布局和平面优化" caption="去耦靠近电源脚，过孔阵列避免切断电源平面；电源换层以多过孔分流。" sourcePage="16"/></section>
<section id="ground-power"><h2>地弹、分地与分电源</h2><p>AGND、数字 GND、PGND 按功能分区后在指定点连接；功率地与控制地隔离，避免大电流扰动 ADC 与逻辑。多个同压电源域可在源头单点连接或用磁珠/0Ω 分隔，防止通道间互相调制。</p><ArticleFigure src="images/knowledge/si-pi/ground-partition.webp" fullSrc="images/knowledge/si-pi/ground-partition-hd.jpg" alt="AGND GND PGND 分区" caption="三个地最终相连，但 PCB 上按电流路径分开，在指定单点汇接。" sourcePage="17"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>PDN 目标阻抗怎样算？</summary><p>用允许电压波动除以最大电流阶跃，并要求在目标频段内保持低于该值。</p></details><details><summary>VSENSE 为什么不能取在稳压器附近？</summary><p>那样无法补偿稳压器到负载之间铜皮和过孔的动态压降。</p></details><details><summary>去耦为什么不能只堆大电容？</summary><p>大电容的 ESL/封装限制高频能力，需要不同容值和封装按频段接力。</p></details></section></>}
