import ArticleFigure from "../ArticleFigure.jsx";

export default function Rs232Rs485Article() {
  return <>
    <section id="rs232-intro"><h2>RS232 接口与电平</h2><p>RS232 是非同步、全双工、点对点接口，双方约定波特率、数据位、校验和停止位。TX/RX 需交叉：逻辑 1 为 −15~−3V，逻辑 0 为 +3~+15V；常用于 PC、PLC 与扫码枪等，典型距离不超过 15m、速率低于 2Mbps。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs232-wiring.webp" fullSrc="images/knowledge/high-speed-interfaces/rs232-wiring-hd.jpg" alt="RS232 DB9 直连与交叉线" caption="点对点连接至少用 TX、RX、GND；DTE/DCE 角色决定直连或 2/3 脚交叉。" sourcePage="25" /></section>
    <section id="rs232-circuits"><h2>RS232 电路设计：SP3232E</h2><p>SP3232E 用电荷泵把 3.3~5V CMOS 电平转换为正负 RS232 电平。C1/C2 与 V+/V− 外接 100nF；连接器侧串 100Ω 并用 15V 双向 TVS，金属壳接 PE，PE 与数字地可经 10nF 隔离耦合。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs232-sp3232.webp" fullSrc="images/knowledge/high-speed-interfaces/rs232-sp3232-hd.jpg" alt="SP3232E RS232 接口电路" caption="主控侧串 22Ω，接口侧串阻与 TVS 靠近 DB9；TVS 工作电压需覆盖 ±15V 合法信号。" sourcePage="26" /></section>
    <section id="rs232-waveform"><h2>RS232 波形解读</h2><p>9600-N-8-1 发送 0xAA 时，线上先出现起始位 0，再按 LSB first 发送 10101010，最后停止位 1；收发器把 −9.6V/＋8.2V 反相转换为 MCU 的高/低电平。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs232-waveform.webp" fullSrc="images/knowledge/high-speed-interfaces/rs232-waveform-hd.jpg" alt="RS232 与 CMOS 波形" caption="RS232 负电压代表逻辑 1，经过 R1OUT 后恢复为 MCU 可识别的正逻辑。" sourcePage="27" /></section>
    <section id="rs485-intro"><h2>RS485 接口与差分电平</h2><p>RS485 是非同步、半双工、多节点差分总线。合法共模范围约 −7~+12V，典型差模为 ±2~6V；接收器只需 A−B 超过 ±200mV 判决。它可在低速时延伸到约 1200m，在 10m 左右做到 10~20Mbps。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs485-threshold-table.webp" fullSrc="images/knowledge/high-speed-interfaces/rs485-threshold-table-hd.jpg" alt="RS485 差分输入阈值" caption="接收门限以 A−B 为准，正向超过 +200mV 判 1，低于 −200mV 判 0。" sourcePage="29" /></section>
    <section id="rs485-circuits"><h2>RS485 电路设计：SP3485</h2><p>SP3485 的 RE# 与 DE 常并联控制方向：高电平发送、低电平接收。总线两端预留 120Ω 端接，按 6V 最坏差模估算功耗 0.3W，留一倍余量宜选 2512；偏置电阻防止悬空，A/B 还需串阻、共模/差模 TVS 与浪涌防护。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs485-sp3485.webp" fullSrc="images/knowledge/high-speed-interfaces/rs485-sp3485-hd.jpg" alt="SP3485 RS485 电路" caption="方向控制、120Ω 端接、偏置与三级防护共同决定空闲稳定性和工业现场可靠性。" sourcePage="29" /><ArticleFigure src="images/knowledge/high-speed-interfaces/rs485-pinout.webp" fullSrc="images/knowledge/high-speed-interfaces/rs485-pinout-hd.jpg" alt="RS485 收发器引脚与方向" caption="RO/RE#/DE/DI 属于 CMOS 侧，A/B 属于差分线侧；RE# 低有效、DE 高有效。" sourcePage="30" /></section>
    <section id="rs485-waveform"><h2>RS485 波形解读</h2><p>4MHz 方波实测中，A/B 都带有相似共模扰动，而数学通道 A−B 得到约 ±1.76V 的干净差分信号。双绞线让外界噪声同时耦合到两根线，接收端做差后抵消，这就是抗干扰核心。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/rs485-waveform.webp" fullSrc="images/knowledge/high-speed-interfaces/rs485-waveform-hd.jpg" alt="RS485 A B 与差分波形" caption="观察 A、B 单端波形之外，还应使用数学通道检查 A−B 的差模幅度和过零。" sourcePage="31" /></section>
    <section id="compare"><h2>四类接口对比</h2><div className="comparison-table-wrap"><table className="comparison-table"><caption>IIC、SPI、RS232 与 RS485</caption><thead><tr><th scope="col">接口</th><th scope="col">同步/方向</th><th scope="col">拓扑与场景</th></tr></thead><tbody><tr><th scope="row">IIC</th><td>同步半双工</td><td>板内地址总线，100k/400k/3.4M</td></tr><tr><th scope="row">SPI</th><td>同步全双工</td><td>板内点对点，常见至 100MHz</td></tr><tr><th scope="row">RS232</th><td>异步全双工</td><td>点对点、约 15m、抗扰弱</td></tr><tr><th scope="row">RS485</th><td>异步半双工</td><td>多节点差分、长距离工业现场</td></tr></tbody></table></div></section>
    <section id="interview"><h2>面试自测</h2><details><summary>RS232 为什么是负逻辑？</summary><p>标准规定负电压区代表逻辑 1、正电压区代表逻辑 0，收发器负责与 CMOS 正逻辑互换。</p></details><details><summary>RS485 为什么抗干扰更强？</summary><p>A/B 承受近似相同的共模干扰，接收器判 A−B 时能抵消它。</p></details><details><summary>120Ω 端接放在哪里？</summary><p>只放在总线物理两端并匹配双绞线特征阻抗，不应每个节点都装。</p></details></section>
  </>;
}
