import ArticleFigure from "../ArticleFigure.jsx";
import WorkedExample from "../WorkedExample.jsx";

export default function SetupHoldTimeArticle() {
  return <>
    <section id="definition"><h2>什么是建立时间与保持时间</h2><p>建立时间是有效采样沿到来前，数据必须稳定的最短时间；保持时间是采样沿之后仍需稳定的最短时间。两者给芯片内部触发器留下判决窗口，裕量不足会产生误码或亚稳态。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/setup-hold-annotation.webp" fullSrc="images/knowledge/high-speed-interfaces/setup-hold-annotation-hd.jpg" alt="建立保持时间标注" caption="以上升沿采样为例：数据完成跳变到采样沿为建立时间，采样沿到下一次数据跳变为保持时间。" sourcePage="20" /></section>
    <section id="measure"><h2>用示波器测量建立保持时间</h2><p>同时探测 CLK 与 DATA，在有效采样沿放时间光标。测量门限必须采用器件时序图规定的阈值（常见是某个输入门限或幅度百分比），不能统一套用 10%/90% 边沿口径。CH390 SPI 的输入建立时间最小 3ns、保持时间最小 2ns；实测还要覆盖手册指定的电压、温度和负载条件。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/setup-hold-ch390.webp" fullSrc="images/knowledge/high-speed-interfaces/setup-hold-ch390-hd.jpg" alt="CH390 SPI 时序参数" caption="T4/T5 分别规定输入建立与保持时间；频率合格不代表采样窗口一定合格。" sourcePage="21" /><WorkedExample title="SPI 采样裕量判断" given={["手册要求 tSU≥3ns、tH≥2ns", "按手册门限测得数据在采样沿前 5.4ns 稳定，采样沿后 3.1ns 才变化"]} calculation={["建立裕量=5.4−3=2.4ns", "保持裕量=3.1−2=1.1ns"]} verification={["两项均为正，当前温度电压下满足", "仍应覆盖高低温、电压偏差与探头负载"]} answer="当前建立和保持分别剩 2.4ns、1.1ns 裕量，保持侧更危险。" /></section>
    <section id="scope-vs-la"><h2>示波器与逻辑分析仪</h2><p>示波器回答“电气波形是否健康”：幅值、阈值、边沿、振铃、串扰与建立保持；逻辑分析仪回答“协议数据是什么”：长时间捕获、多通道、解码和二/十/十六进制转换。前者通常只有 2~4 通道，后者看不到模拟细节且常受 100MHz 左右采样率限制。</p><ArticleFigure src="images/knowledge/high-speed-interfaces/scope-logic-analyzer.webp" fullSrc="images/knowledge/high-speed-interfaces/scope-logic-analyzer-hd.jpg" alt="示波器与逻辑分析仪对比" caption="示波器看波形质量，逻辑分析仪看长记录和协议；两者共地并选择足够采样率。" sourcePage="23" /></section>
    <section id="workflow"><h2>软硬件联合调试步骤</h2><div className="application-list"><article><h3>先读手册</h3><p>确认 IO 阈值、采样边沿、建立保持、最大 SCK 与输出延迟。</p></article><article><h3>再看模拟波形</h3><p>用短地弹簧探测，测幅值、单调性、振铃与时序；降频若恢复，只能说明问题与周期或边沿相关，仍需定量定位。</p></article><article><h3>最后抓长协议</h3><p>逻辑分析仪记录长协议，核对模式、字节顺序、地址、ACK 与异常前后的上下文。</p></article></div><aside className="article-callout"><strong>保持违例的处理：</strong>降低频率不一定修复同一采样沿的保持违例，因为它主要由最短数据路径、时钟偏斜和器件输出延迟决定。应调整采样相位/时钟偏斜、增加受控的数据路径延迟或按接口规范修改时序；任何改动都要同时重算建立与保持裕量。</aside></section>
    <section id="interview"><h2>面试自测</h2><details><summary>建立与保持时间分别在哪一侧量？</summary><p>建立量采样沿之前的数据稳定区，保持量采样沿之后的数据稳定区。</p></details><details><summary>为何只用逻辑分析仪不能验证时序质量？</summary><p>它把模拟电压阈值化，无法可靠展示幅值、振铃、边沿和阈值交越细节。</p></details><details><summary>降频后通信恢复说明什么？</summary><p>强烈提示采样裕量、边沿质量、反射或串扰问题，但仍需示波器和手册定量确认。</p></details></section>
  </>;
}
