import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
import WorkedExample from "../WorkedExample.jsx";
export default function SiMeasurementArticle(){return <>
<section id="bandwidth"><h2>上升时间与信号带宽</h2><p>正弦波频率等于带宽；近似方波包含丰富谐波，按 10%~90% 上升时间估算 <FormulaText text="BW≈0.35/t_r" />。因此 25MHz 时钟若 tr=4ns，边沿带宽约 87.5MHz，不能只按 25MHz 选探头和布局规则。</p><ArticleFigure src="images/knowledge/si-pi/rise-time-bandwidth.webp" fullSrc="images/knowledge/si-pi/rise-time-bandwidth-hd.jpg" alt="上升时间与带宽" caption="边沿越陡，等效带宽越高；信号频率与边沿带宽必须分开。" sourcePage="37"/></section>
<section id="high-speed"><h2>什么时候算高速信号</h2><p>速率本身高、手册给出很陡 tr/tf、链路趋肤/介质损耗明显，或走线长度超过上升沿对应波长的 1/6，都应按高速设计。FR4 内传播约 1.5×10^8m/s。</p><ArticleFigure src="images/knowledge/si-pi/one-sixth-wavelength.webp" fullSrc="images/knowledge/si-pi/one-sixth-wavelength-hd.jpg" alt="一比六波长高速判断" caption="1ns 边沿约 350MHz，FR4 波长约 0.42m，1/6 约 70mm；超过后必须考虑传输线。" sourcePage="40"/><WorkedExample title="1ns 边沿的高速边界" given={["tr=1ns","FR4 传播速度约 1.5×10^8m/s"]} calculation={["BW=0.35/1ns=350MHz","λ=v/f≈0.43m，λ/6≈71mm"]} verification={["走线还要加封装、过孔与连接器电气长度","规则用于判断，不替代仿真"]} answer="约 70mm 以上应明确按传输线和阻抗连续设计。"/></section>
<section id="vna"><h2>插损、回损与 VNA</h2><p>插损随频率和距离增大。VNA 的 S21 表示端口 1 到端口 2 的传输（插损），S11 表示端口 1 反射（回损）；测试前先按扫描频段做两端口校准，再连接 DUT。</p><ArticleFigure src="images/knowledge/si-pi/insertion-loss-distance.webp" fullSrc="images/knowledge/si-pi/insertion-loss-distance-hd.jpg" alt="FR4 走线插损随距离频率" caption="同为 4mil FR4，8/16/24inch 越长，高频插损越大。" sourcePage="42"/><ArticleFigure src="images/knowledge/si-pi/vna-sparams-test.webp" fullSrc="images/knowledge/si-pi/vna-sparams-test-hd.jpg" alt="VNA 两端口插损测试" caption="校准去除探头/线缆损耗后，S21 才代表被测传输路径本身。" sourcePage="43"/></section>
<section id="tdr"><h2>TDR 阻抗与位置定位</h2><p>TDR 向链路发阶跃并把反射换算为阻抗。时间越小越靠近连接器，时间越大越靠近远端；已知传播速度即可定位异常。窄线/小电容呈高阻上抬，宽线/焊盘电容呈低阻下凹，开路最终上升到无穷。</p><ArticleFigure src="images/knowledge/si-pi/tdr-impedance-profile.webp" fullSrc="images/knowledge/si-pi/tdr-impedance-profile-hd.jpg" alt="TDR 阻抗剖面" caption="连接器、线宽突变与开路分别在时间轴上形成可定位的阻抗台阶。" sourcePage="44"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>100MHz 方波带宽一定是 100MHz 吗？</summary><p>不是，应主要按上升时间用 0.35/tr 估算边沿带宽。</p></details><details><summary>S21 与 S11 各表示什么？</summary><p>S21 是正向传输/插损，S11 是输入反射/回损。</p></details><details><summary>TDR 如何定位故障？</summary><p>反射到达时间乘传播速度并考虑往返，可换算到阻抗突变的物理位置。</p></details></section></>}
