import ArticleFigure from "../ArticleFigure.jsx";
export default function SiRoutingArticle(){return <>
<section id="impedance"><h2>阻抗连续与扇出</h2><p>传输路径从芯片焊盘、扇出、走线、过孔、器件到连接器都要维持协议要求的 50/85/90/100Ω。BGA 区因 pitch 限制可短距离缩线宽/线距，离开扇出区应立即恢复层叠计算值。</p><ArticleFigure src="images/knowledge/si-pi/interface-impedance-tables.webp" fullSrc="images/knowledge/si-pi/interface-impedance-tables-hd.jpg" alt="常见接口阻抗表" caption="eMMC/SDIO 单端 50Ω，HDMI/MIPI 100Ω，USB 90Ω，PCIE 85Ω 左右。" sourcePage="68"/><ArticleFigure src="images/knowledge/si-pi/bga-breakout-impedance.webp" fullSrc="images/knowledge/si-pi/bga-breakout-impedance-hd.jpg" alt="BGA 扇出阻抗恢复" caption="扇出区短暂用 4/4mil，出 BGA 后恢复 6/8mil 等目标阻抗结构。" sourcePage="70"/></section>
<section id="reference"><h2>参考平面与伴地孔</h2><p>高频回流集中在信号正下方，完整低阻 GND 参考优于电源平面。不要跨分割或换参考网；无法避免时在近处放缝合电容。信号换层时加伴地孔，把两个 GND 参考层直接连起来；高速差分建议每对至少两个对称伴地孔。</p><ArticleFigure src="images/knowledge/si-pi/return-current-density.webp" fullSrc="images/knowledge/si-pi/return-current-density-hd.jpg" alt="回流电流随频率分布" caption="频率越高，回流越贴近走线正下方；跨分割会迫使回流绕行并放大环路。" sourcePage="71"/><ArticleFigure src="images/knowledge/si-pi/stitching-via-return.webp" fullSrc="images/knowledge/si-pi/stitching-via-return-hd.jpg" alt="换层伴地孔" caption="对称伴地孔缩短 L2→L5 参考层回流，降低阻抗突变、插损与 EMI。" sourcePage="72"/></section>
<section id="vias"><h2>残桩、背钻与 HDI</h2><p>通孔未参与信号的金属段形成 stub，引入寄生电感、谐振和反射。5Gbps 以上或多次换层时考虑背钻，或用 HDI 盲/埋孔消除残桩；普通 PTH 每条 TX/RX 通道常控制在 2 个以内。</p><ArticleFigure src="images/knowledge/si-pi/via-stub-backdrill.webp" fullSrc="images/knowledge/si-pi/via-stub-backdrill-hd.jpg" alt="通孔残桩与背钻" caption="背钻从反面去除未使用孔铜，但要精确控深且增加制造成本。" sourcePage="74"/><ArticleFigure src="images/knowledge/si-pi/blind-buried-vias.webp" fullSrc="images/knowledge/si-pi/blind-buried-vias-hd.jpg" alt="通孔盲孔埋孔" caption="HDI 盲埋孔只跨目标层，无多余残桩，适合高密度高速板。" sourcePage="75"/></section>
<section id="symmetry"><h2>焊盘挖空与差分对称</h2><p>耦合电容、TVS、连接器和金手指焊盘比走线宽，增加对参考层电容并拉低阻抗；可局部挖空相邻参考层补偿。差分扇出、换层、器件与过孔必须对称、等间距、紧耦合，避免差模转共模。</p><ArticleFigure src="images/knowledge/si-pi/pad-voiding.webp" fullSrc="images/knowledge/si-pi/pad-voiding-hd.jpg" alt="器件焊盘参考层挖空" caption="8Gbps 以上差分在耦合电容和连接器焊盘下挖参考，减小额外寄生电容。" sourcePage="76"/><ArticleFigure src="images/knowledge/si-pi/differential-breakout-symmetry.webp" fullSrc="images/knowledge/si-pi/differential-breakout-symmetry-hd.jpg" alt="差分对称扇出" caption="不对称扇出、焊盘或过孔把差模能量转成共模，导致 EMI 与反射。" sourcePage="78"/></section>
<section id="materials"><h2>间距、板材与玻纤效应</h2><p>差分对与其他信号建议 5W，普通单端至少 3W；相邻层尽量拉开 4~6H 或正交。高速板材关注低 Df、低 CTE 和高 Tg。P/N 分别压在玻纤束与树脂区会看到不同介电常数，可旋转/zigzag 走线或选更均匀玻纤布。</p><ArticleFigure src="images/knowledge/si-pi/differential-spacing.webp" fullSrc="images/knowledge/si-pi/differential-spacing-hd.jpg" alt="差分对间距" caption="5W 指边缘间距；相邻层差分还要拉开 4~6H，降低串扰。" sourcePage="80"/><ArticleFigure src="images/knowledge/si-pi/fiber-weave-effect.webp" fullSrc="images/knowledge/si-pi/fiber-weave-effect-hd.jpg" alt="PCB 玻纤效应" caption="两根线落在玻纤束与树脂上会产生阻抗/时延差，斜走或 zigzag 可平均介质。" sourcePage="86"/></section>
<section id="offboard"><h2>跨板、线缆与中继</h2><p>跨板优先使用有完整参考层的 FPC 和高速板对板连接器；长距离用同轴、双芯同轴或屏蔽双绞线。Redriver/均衡器补偿频率相关插损，Retimer 还能恢复时钟、重整抖动和码型。</p><ArticleFigure src="images/knowledge/si-pi/fpc-coax-twinax.webp" fullSrc="images/knowledge/si-pi/fpc-coax-twinax-hd.jpg" alt="同轴与双芯同轴线缆" caption="同轴单端 45/50Ω，两根可组成 90/100Ω 差分；屏蔽提供稳定参考与回流。" sourcePage="83"/><ArticleFigure src="images/knowledge/si-pi/equalizer-redriver.webp" fullSrc="images/knowledge/si-pi/equalizer-redriver-hd.jpg" alt="均衡器前后眼图" caption="2.5Gbps 经 70inch FR4 后眼图闭合，Redriver EQ 可补高频并重新开眼。" sourcePage="85"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>信号换层为什么要伴地孔？</summary><p>给高频回流提供就近跨层路径，避免绕远导致环路、阻抗和 EMI 增大。</p></details><details><summary>背钻解决什么问题？</summary><p>去除通孔未使用段的残桩，降低谐振和反射。</p></details><details><summary>Redriver 与 Retimer 区别？</summary><p>Redriver 做模拟均衡/放大；Retimer 还恢复时钟并重新定时数据。</p></details></section></>}
