import ArticleFigure from "../ArticleFigure.jsx";
import FormulaText from "../FormulaText.jsx";
import WorkedExample from "../WorkedExample.jsx";
export default function TransmissionLineTerminationArticle(){return <>
<section id="transmission-line"><h2>传输线与特征阻抗</h2><p>PCB 走线由连续分布的电容和电感组成，阶跃只影响前沿到达的局部区域，瞬时电压/电流比表现为特征阻抗。均匀结构下 Z0 由单位长度 L/C、介质与几何决定，与线长和信号频率本身无直接关系。</p><ArticleFigure src="images/knowledge/si-pi/transmission-line-model.webp" fullSrc="images/knowledge/si-pi/transmission-line-model-hd.jpg" alt="传输线分布电容模型" caption="信号每前进一小段就给该段分布电容充电，电磁场沿参考平面传播。" sourcePage="20"/></section>
<section id="impedance-control"><h2>阻抗控制与参考平面</h2><p>微带阻抗受线宽 W、铜厚 t、介电常数 εr、层距 h 共同影响。单端常用 50Ω，LVDS/MIPI/HDMI/千兆 MDI 为 100Ω 差分，USB 为 90Ω，PCIE 常为 80~90Ω。参考平面必须完整连续。</p><ArticleFigure src="images/knowledge/si-pi/microstrip-impedance.webp" fullSrc="images/knowledge/si-pi/microstrip-impedance-hd.jpg" alt="微带线阻抗公式" caption="加宽走线或减小层距通常降低阻抗；层叠确定后应由板厂场求解并给出线宽线距。" sourcePage="22"/></section>
<section id="reflection"><h2>反射系数与振铃</h2><p>阻抗突变时 <FormulaText text="ρ=(Z_2-Z_1)/(Z_2+Z_1)" />。开路 ρ=+1，末端瞬时电压可翻倍；短路 ρ=−1，末端电压抵消。反射在源端和负载之间往返，叠加成台阶、过冲和振铃。</p><ArticleFigure src="images/knowledge/si-pi/reflection-ringing.webp" fullSrc="images/knowledge/si-pi/reflection-ringing-hd.jpg" alt="多次反射形成振铃" caption="边沿台阶与逐渐衰减的振荡都来自阻抗不连续后的多次往返反射。" sourcePage="25"/><WorkedExample title="50Ω 传输线遇到 100Ω 负载" given={["Z1=50Ω，Z2=100Ω","入射阶跃 1V"]} calculation={["ρ=(100−50)/(100+50)=1/3","首次反射电压=1V/3，负载瞬时升至 1.33V"]} verification={["负载大于线阻抗，因此为正反射","源端阻抗还会决定后续往返反射"]} answer="首次正反射系数 1/3，负载电压先到 1.33V，再经过多次反射收敛。"/></section>
<section id="terminations"><h2>源端、并联、戴维宁与 RC 端接</h2><p>源端串联把驱动内阻加到 Z0，电阻必须靠近发送端；并联端接放接收端但持续耗电；戴维宁用上下拉既匹配又设共模；RC 端接隔绝直流、只在边沿期间吸收能量。DDR fly-by 地址命令线在菊花链末端接 40~50Ω 到 VTT。</p><ArticleFigure src="images/knowledge/si-pi/source-termination.webp" fullSrc="images/knowledge/si-pi/source-termination-hd.jpg" alt="源端串联端接" caption="若驱动约 30Ω，串 20~22Ω 可接近 50Ω；RGMII 串阻按信号方向放在真正发送端。" sourcePage="27"/><ArticleFigure src="images/knowledge/si-pi/ddr-flyby-termination.webp" fullSrc="images/knowledge/si-pi/ddr-flyby-termination-hd.jpg" alt="DDR fly-by 末端端接" caption="地址命令沿菊花链传播，在物理末端用 40~50Ω 端接到 VTT。" sourcePage="29"/><ArticleFigure src="images/knowledge/si-pi/rc-termination.webp" fullSrc="images/knowledge/si-pi/rc-termination-hd.jpg" alt="RC 端接" caption="串联电容只让交流边沿看到端接电阻，减少静态功耗；参数仍需按拓扑仿真。" sourcePage="31"/></section>
<section id="differential-odt"><h2>差分端接与 ODT</h2><p>100Ω 差分端接应位于接收端；外部电阻与芯片内部端接只能选一处。ODT 从 DDR2 起用寄存器控制 die 内 DQ/DQS/DM 端接，读写方向变化时动态切换，减少 PCB 器件和残桩，但阻值会受 PVT 影响。</p><ArticleFigure src="images/knowledge/si-pi/ddr-odt-read-write.webp" fullSrc="images/knowledge/si-pi/ddr-odt-read-write-hd.jpg" alt="DDR ODT 读写切换" caption="写入时 DDR 端接，读取时控制器端接；端接始终位于当前接收端。" sourcePage="35"/></section>
<section id="interview"><h2>面试自测</h2><details><summary>开路和短路的反射系数？</summary><p>开路 +1，短路 −1。</p></details><details><summary>源端串阻为什么要靠发送端？</summary><p>要在反射发生前把驱动阻抗与线阻抗配平，远离源端会形成未端接残桩。</p></details><details><summary>内部端接与外部端接能否同时开？</summary><p>不能；并联后阻抗减半，会造成新的失配和幅值下降。</p></details></section></>}
